name: Upload artifacts
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  release_compiled_program:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v4

      - name: check for cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        id: cache-packages
        with:
          packages: mingw-w64 g++
          version: 1.0
          execute_install_scripts: true
      - name: install packages
        if: ${{ startsWith(github.ref, 'refs/tags/') && steps.cache-packages.outputs.cache-hit != 'true'}}
        run: sudo apt update && sudo apt install mingw-w64 g++ -y

      - name: compile
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          /usr/bin/x86_64-w64-mingw32-g++-win32 -std=c++20 -Wall -fdiagnostics-color=always -static -o output.exe *.cpp
          g++ -std=c++20 -Wall -o output.out *.cpp
          mv output.out main.out
          mv output.exe main.exe

      - name: release the compiled program
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "main.exe,main.out"
          allowUpdates: true

